baseURL: http://www.yunyitang.me/ # 绑定的域名
languageCode: en
title: Yunyi's Blog
theme: PaperMod 

# change config for posts:
# hugo convert toYAML --config config.yml --unsafe --verbose
# hugo --config config.yml
# before push github: 
# hugo -F --cleanDestinationDir
# local preview: hugo server -D

enableInlineShortcodes: true
enableEmoji: true # 允许使用 Emoji 表情，建议 true
enableRobotsTXT: true # 允许爬虫抓取到搜索引擎，建议 true
hasCJKLanguage: true # 自动检测是否包含 中文日文韩文 如果文章中使用了很多中文引号的话可以开启

defaultContentLanguage: en
defaultContentLanguageInSubdir: true

languages:
    en:
        languageName: English
        languageCode: en
        contentDir: content/English
        menu:
          main:
            - identifier: about
              name: About
              url: /en/about/
              weight: 10
            - identifier: project
              name: Project
              url: /en/project/
              weight: 20
            - identifier: resume
              name: Resume
              url: /en/resume.pdf
              weight: 30
            - identifier: tags
              name: 🕹️
              url: /en/tags/
              weight: 40
            - identifier: search
              name: Search
              url: /en/search/
              weight: 50
        profileMode:
          enabled: true
          title: Yunyi Tang
          subtitle: Little squirrel Hopping around
          imageUrl: "img/Avatar.png"
          imageTitle: 
          imageWidth: 150
          imageHeight: 150
          buttons:
            - name: About
              url: /en/about/
            - name: Project
              url: /en/project/
            - name: Resume
              url: /en/resume.pdf
            - name: Log
              url: /en/blog/tech/log/
    zh:
        languageName: 中文
        languageCode: zh
        contentDir: content/Chinese
        menu:
          main:
            - identifier: about
              name: 关于
              url: /zh/about/
              weight: 10
            - identifier: project
              name: 项目
              url: /zh/project/
              weight: 20
            - identifier: resume
              name: 简历
              url: /zh/resume.pdf
              weight: 30
            - identifier: blog
              name: 博客
              url: /zh/blog/
              weight: 40
            - identifier: links
              name: 友链
              url: /zh/links/
              weight: 50
            - identifier: tags
              name: 🕹️
              url: /zh/tags/
              weight: 60
            - identifier: search
              name: 搜索
              url: /zh/search/
              weight: 70
        profileMode:
          enabled: true
          title: Yunyi Tang
          subtitle: Little squirrel Hopping around
          imageUrl: "img/Avatar.png"
          imageTitle: 
          imageWidth: 150
          imageHeight: 150
          buttons:
            - name: 关于
              url: /zh/about/
            - name: 项目
              url: /zh/project/
            - name: 简历
              url: /zh/resume.pdf
            - name: 👩🏻‍💻
              url: /zh/blog/tech/

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary for the search function

# 这里的参数会被代码以 .Site.Params 的形式读取
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Yunyi's blog, tech, life, data, 技术博客"
  author: Yunyi
  defaultTheme: auto  # defaultTheme: light or  dark 
  disableThemeToggle: false
  DateFormat: "2006-01-02"
  ShowShareButtons: false
  ShowReadingTime: true
  # disableSpecialistPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideFooter: false # 隐藏页脚
  ShowWordCounts: true
  VisitCount: true
  ShowLastMod: true #显示文章更新时间

  ShowToc: true # 显示目录
  TocOpen: true # 自动展开目录

  extendCodeBackground: false # 代码块是否自动横向展开

  comments: true 
  twikoo: 
      version: 1.6.27 # 这个版本号要自己手动修改，和twikoo的版本号要对得上
      # tkserver - bdayTtyy!
      # MangoDB yunyit - HsdK3JAKhZbsUnAq Gmail-longin
      # mongodb+srv://yunyit:HsdK3JAKhZbsUnAq@cluster0.p9y20lj.mongodb.net/?retryWrites=true&w=majority
      # https://vercel.com/yunyis-projects/twikoo-api/C5MeWSz2yNXj3RqBa7t23BxjYQDJ 


  socialIcons:
    - name: github
      url: "https://github.com/yunyit"
    - name: linkedin
      url: "https://www.linkedin.com/in/yunyitang820/"
    - name: instagram
      url: "https://www.instagram.com/yunyi_cam/"
    - name: goodreads
      url: "https://www.goodreads.com/user/show/161105203-yunyi-tang"
    - name: email
      url: "mailto:yunyi.tang.820@gmail.com"

  label:
    text: "Home"
    # icon: "img/Icon.png"
    iconHeight: 35
  
  assets:
    # disableHLJS: true 
    favicon: "favicon_io/favicon.ico"
    favicon16x16: "favicon_io/favicon-16x16.png"
    favicon32x32: "favicon_io/favicon-32x32.png"
    apple_touch_icon: "favicon_io/apple-touch-icon.png"
    safari_pinned_tab: "img/Icon.svg"